---
# handlers file for Nexus
- name: Reload systemd
  ansible.builtin.systemd:
    daemon-reload: yes
    name: nexus.service
  listen: systemd-reload

- name: Nexus systemd service restart
  ansible.builtin.systemd:
    name: nexus.service
    state: restarted
    no_block: yes
  listen: nexus-service-restart
  when: "ansible_service_mgr == 'systemd'"

- name: Nexus sysv service restart
  ansible.builtin.service:
    name: nexus
    state: restarted
  listen: nexus-service-restart
  when: "ansible_service_mgr != 'systemd'"

- name: Nexus systemd service stop
  ansible.builtin.systemd:
    name: nexus.service
    state: stopped
  listen: nexus-service-stop
  when: nexus_systemd_service_file.stat.exists

- name: Nexus sysv service stop
  ansible.builtin.service:
    name: nexus
    state: stopped
  listen: nexus-service-stop
  when: nexus_sysv_service_file.stat.exists

- name: Wait for Apache port to be available
  ansible.builtin.wait_for:
    port: 443
    delay: 5
  listen: wait-for-httpd